import { describe, expect, it } from 'vitest'
import { paths, verifyPaths, verifyClone } from './helpers/storyPaths'
import { withGhostMarriageConsequences } from '../src/story/episodes/ghostMarriageConsequences'
it('decorator does not mutate supplied chapter or nested memories', () => verifyClone(episode, withGhostMarriageConsequences))
const { episode, play, pick, body, result, legacy, options } = paths('ghost-marriage')
describe('marriage, evidence and consent stay separate', () => {
  it('does not roll a completed thirty-two-person debt verification back to pending', () => {
    const end = play(['ghost-q1-investigate', 'ghost-investigate-q2-workers', 'ghost-investigate-q3-open', 'ghost-investigate-q4-ledger', 'ghost-investigate-q5-debt'])
    expect(body(end)).toMatch(/完成了三十二笔/)
    expect(body(end)).not.toMatch(/其他人的债权仍逐人另查|三十二份申报仍须逐一确认/)
  })
  it('remembers opening method and does not turn meeting Ayun into agreed guardianship', () => {
    const opened = play(['ghost-q1-marriage', 'ghost-marriage-q2-open'])
    const together = play(['ghost-q1-marriage', 'ghost-marriage-q2-lian'])
    expect(body(opened)).toMatch(/丈夫.*(开箱|木箱)|木箱.*丈夫/)
    expect(body(together)).toMatch(/徐莲.*(共同|开箱|发簪)/)
    const fourth = pick(opened, 'ghost-marriage-q3-accept')
    const fifth = pick(fourth, 'ghost-marriage-q4-will')
    expect(body(fifth)).toMatch(/阿芸[\s\S]*没答应过继/)
    expect(body(pick(fifth, 'ghost-marriage-q5-stay'))).toMatch(/阿芸/)
    const proposed = pick(pick(together, 'ghost-marriage-q3-contract'), 'ghost-marriage-q4-sign')
    expect(body(proposed)).toMatch(/附约.*(未|没有)|未.*批准/)
    expect(body(proposed)).toMatch(/补签/)
  })
  it('keeps modern separate signature handling distinct from a legacy signature on the original', () => {
    const fourth = play(['ghost-q1-marriage', 'ghost-marriage-q2-lian', 'ghost-marriage-q3-contract'])
    const fresh = result(fourth, 'ghost-marriage-q4-sign')
    expect(body(fresh)).toMatch(/附页|附纸/)
    expect(fresh.tags).toContain('willSignatureSeparated')
    const old = legacy('result-ghost-marriage-q4-sign', ['routeMarriage', 'openedWithLian', 'guardianshipTerms', 'willCountersigned'])
    expect(body(old)).not.toMatch(/你把签名写在附页|原信没有新增/)
    expect(body(old)).toMatch(/补签|旧信/)
  })
  it('recalls wage/debt findings and full disclosure whether kept or postponed', () => {
    expect(body(play(['ghost-q1-investigate', 'ghost-investigate-q2-workers']))).toMatch(/欠薪/)
    expect(body(play(['ghost-q1-investigate', 'ghost-investigate-q2-debt']))).toMatch(/死后/)
    const pact = play(['ghost-q1-investigate', 'ghost-investigate-q2-debt', 'ghost-investigate-q3-terms'])
    expect(options(pact).map((c) => c.id)).toContain('ghost-investigate-q4-public')
    const publicEnd = pick(pick(pact, 'ghost-investigate-q4-public'), 'ghost-investigate-q5-will')
    expect(body(publicEnd)).toMatch(/徐莲[\s\S]*(约定|答应|完整)/)
    const temp = pick(pact, 'ghost-investigate-q4-temporary')
    expect(body(temp)).toMatch(/已生效的婚书/)
    expect(body(temp)).toMatch(/公开.*(尚|未)|未.*公开/)
    const tempEnd = pick(temp, 'ghost-investigate-q5-will')
    expect(body(tempEnd)).toMatch(/撤销/)
    expect(body(tempEnd)).not.toContain('顾言没有成为丈夫')
  })
  it('retains family/evidence packing, Lian’s autonomous choice and actual handover', () => {
    const family = play(['ghost-q1-refuse', 'ghost-refuse-q2-family'])
    const proof = play(['ghost-q1-refuse', 'ghost-refuse-q2-ledger'])
    expect(body(family)).toMatch(/箱|药材/)
    expect(body(proof)).toMatch(/七日|日期/)
    const copied = pick(family, 'ghost-refuse-q3-copy')
    expect(options(copied).map((c) => c.id)).not.toContain('ghost-refuse-q4-will')
    const final = pick(copied, 'ghost-refuse-q4-objection')
    expect(body(final)).not.toContain('希望接受减债')
    const end = pick(final, 'ghost-refuse-q5-ledger')
    expect(body(end)).toMatch(/徐莲.*(决定|许可|同意)/)
    expect(body(end)).toMatch(/异议.*(未|待)|尚未裁定/)
    const key = pick(pick(pick(proof, 'ghost-refuse-q3-copy'), 'ghost-refuse-q4-key'), 'ghost-refuse-q5-cord')
    expect(body(key)).toMatch(/交出.*钥匙|钥匙.*交/)
  })
  for (const relic of ['', 'shared-roster', 'old-badge', 'film-strip']) it(`all routes / ${relic}`, () => verifyPaths(episode, relic))
})
