import { describe, expect, it } from 'vitest'
import { paths, verifyPaths, verifyClone } from './helpers/storyPaths'
import { withMaleSafetyConsequences } from '../src/story/episodes/maleSafetyConsequences'
it('decorator does not mutate supplied chapter or nested memories', () => verifyClone(episode, withMaleSafetyConsequences))
const { episode, play, pick, body, result, legacy, options, settle } = paths('male-safety')
describe('safety records contain only actual actions and permissions', () => {
  it('distinguishes confirming safety from an actual alert through the final report', () => {
    const base = ['safety-q1-comply', 'safety-comply-q2-answer']
    const confirmed = pick(play([...base, 'safety-comply-q3-confirm']), 'safety-comply-q4-exit')
    expect(body(confirmed)).not.toMatch(/你主动报警|警报引发的急刹/)
    expect(body(confirmed)).toMatch(/确认安全/)
    const end = pick(confirmed, 'safety-comply-q5-report')
    expect(body(end)).not.toMatch(/你主动报警|警报引发的急刹/)
    expect(body(end)).toMatch(/确认安全/)
    const alerted = pick(play([...base, 'safety-comply-q3-alert']), 'safety-comply-q4-exit')
    expect(body(pick(alerted, 'safety-comply-q5-report'))).toMatch(/急刹/)
    const mutual = play(['safety-q1-comply', 'safety-comply-q2-question', 'safety-comply-q3-confirm'])
    expect(body(result(mutual, 'safety-comply-q4-together'))).not.toContain('警报引发的急刹')
  })
  it('remembers profile versus mutual data and preserves prior uploads after deletion', () => {
    expect(body(play(['safety-q1-comply', 'safety-comply-q2-answer']))).toMatch(/情绪紧张|档案/)
    expect(body(play(['safety-q1-comply', 'safety-comply-q2-question']))).toMatch(/宋岚.*(音频|记录|保存)/)
    const end = play(['safety-q1-comply', 'safety-comply-q2-answer', 'safety-comply-q3-confirm', 'safety-comply-q4-exit', 'safety-comply-q5-delete'])
    expect(body(end)).toMatch(/已经上传|曾经上传|先前上传/)
  })
  it('does not restart a stopped witness car and recalls informed/covert relations', () => {
    const stopped = play(['safety-q1-witness', 'safety-witness-q2-open', 'safety-witness-q3-stop'])
    expect(body(stopped)).not.toContain('车辆进入高架')
    expect(body(stopped)).toMatch(/仍.*(停|便利店)|已.*停/)
    expect(body(result(stopped, 'safety-witness-q4-code'))).not.toContain('车辆已经回到主路')
    const end = pick(pick(stopped, 'safety-witness-q4-timeline'), 'safety-witness-q5-both')
    expect(body(end)).toMatch(/你说过陈晨在见证/)
    expect(body(end)).toMatch(/已.*停|停车.*时刻/)
    const covert = play(['safety-q1-witness', 'safety-witness-q2-quiet', 'safety-witness-q3-driver', 'safety-witness-q4-exit', 'safety-witness-q5-gap'])
    expect(body(covert)).toMatch(/未说明|没说明|没有告知/)
    expect(body(covert)).toMatch(/陈晨.*(这次|接)/)
  })
  it('grants safety-word agreement only on new actions, not legacy saves', () => {
    const fresh = play(['safety-q1-witness'])
    expect(fresh.tags).toContain('safetyWordAgreed')
    const old = legacy('q4-witness', ['routeWitness', 'covertWitness', 'witnessedStop'])
    expect(options(old).map((c) => c.id)).not.toContain('safety-witness-q4-code')
    expect(body(legacy('result-q1-witness', ['routeWitness']))).not.toContain('一分钟无回应')
    expect(body(legacy('result-safety-witness-q4-exit', ['routeWitness', 'friendPickup']))).not.toContain('陈晨答应这次')
    const loadedCode = legacy('result-safety-witness-q4-code', ['routeWitness', 'safetyWordUsed'])
    expect(body(loadedCode)).toMatch(/(没有|未).*约定|未.*确认/)
    expect(body(settle(loadedCode))).not.toContain('已按约定')
  })
  it('recalls recording/photograph scope and only compares voluntarily provided footage', () => {
    expect(body(play(['safety-q1-private', 'safety-private-q2-tell']))).toMatch(/宋岚.*告知后才打开音频/)
    const paired = play(['safety-q1-private', 'safety-private-q2-tell', 'safety-private-q3-photo'])
    expect(body(paired)).toMatch(/照片/)
    expect(body(result(paired, 'safety-private-q4-pair'))).toMatch(/(询问|请求).*宋岚|宋岚.*(愿意|同意)/)
    const end = pick(pick(paired, 'safety-private-q4-pair'), 'safety-private-q5-protocol')
    expect(body(end)).toMatch(/照片/)
    expect(body(end)).toMatch(/草案|试用/)
    const noted = play(['safety-q1-private', 'safety-private-q2-hide', 'safety-private-q3-map', 'safety-private-q4-share', 'safety-private-q5-local'])
    expect(body(noted)).toMatch(/路口/)
    expect(body(noted)).toMatch(/未告知|没有告知|没告诉宋岚/)
  })
  it('legacy minimal notes and early end do not invent later audio or continuing in-car travel', () => {
    const old = legacy('q4-private', ['routePrivate', 'minimalLog', 'rideEndedEarly'])
    expect(body(old)).not.toContain('主动锁上车门')
    expect(body(old)).toMatch(/订单.*(结束|已)|已.*结束/)
    const resultState = result(old, 'safety-private-q4-share')
    expect(body(resultState)).not.toContain('完整文件')
    expect(body(pick(settle(resultState), 'safety-private-q5-local'))).toMatch(/关闭.*录音|停录/)
  })
  for (const relic of ['', 'unexecuted-will', 'cut-red-cord', 'worker-ledger']) it(`all routes / ${relic}`, () => verifyPaths(episode, relic))
})
