import { describe, expect, it } from 'vitest'
import { paths, verifyPaths, verifyClone } from './helpers/storyPaths'
import { withSpinningJennyConsequences } from '../src/story/episodes/spinningJennyConsequences'
it('decorator does not mutate supplied chapter or nested memories', () => verifyClone(episode, withSpinningJennyConsequences))
const { episode, play, pick, body, result, options, legacy } = paths('spinning-jenny')
describe('machine choices have separate training, approval and actual rescue', () => {
  it('recalls the completed inspection at accountability without reopening the location decision', () => {
    const inspected = play(['jenny-q1-open', 'jenny-open-q2-visit'])
    expect(body(inspected)).toContain('现在谁回原机看着艾达')
    const final = pick(pick(inspected, 'jenny-open-q3-copy'), 'jenny-open-q4-copy')
    expect(final.nodeId).toBe('q5-open')
    expect(body(final)).not.toContain('现在谁回原机看着艾达')
    expect(body(final)).toMatch(/查过缺失的制动器/)
    expect(body(final)).toMatch(/事故时你在仿制机旁，鲁思守原机总闸/)
    expect(body(final)).toMatch(/仿制机已经.*停下/)
  })
  it('does not remove gears on a terms route or undo later confirmed relic-site rescue', () => {
    expect(body(play(['jenny-q1-workers', 'jenny-workers-q2-terms']))).not.toContain('拆下的齿轮仍')
    for (const relic of ['anonymous-dose', 'prison-thread']) {
      let state = play(['jenny-q1-open'])
      state = pick(state, `use-spinning-jenny-open-${relic}`, [relic])
      state = pick(state, `follow-spinning-jenny-open-${relic}`)
      state = pick(state, relic === 'anonymous-dose' ? 'execute-spinning-jenny-open-anonymous-dose' : 'jenny-open-q4-copy')
      const end = pick(state, 'jenny-open-q5-standard')
      expect(body(end)).toMatch(/两处.*(停|断开)/)
      expect(body(end)).not.toMatch(/原机另列待核对|仿制机随后怎样处置仍待/)
      expect(end.tags).not.toContain('safetyPage')
      expect(end.tags).not.toContain('stayedCopy')
    }
  })
  it('Ada remembers her self-stop before and after a blame report', () => {
    const fourth = play(['jenny-q1-owner', 'jenny-owner-q2-drill', 'jenny-owner-q3-speed'])
    const fifth = pick(fourth, 'jenny-owner-q4-ada')
    expect(body(fifth)).toMatch(/艾达[\s\S]*练/)
    expect(body(fifth)).toMatch(/提速|加速|演示速度/)
    const blamed = pick(fifth, 'jenny-owner-q5-blame')
    expect(body(blamed)).toMatch(/艾达[\s\S]*练[\s\S]*(异议|失误|签)/)
    expect(body(blamed)).not.toMatch(/你的掌心|划破.*掌心/)
    expect(body(pick(fifth, 'jenny-owner-q5-recall'))).toMatch(/自己.*停|自行.*停|她.*停机/)
    expect(options(play(['jenny-q1-owner', 'jenny-owner-q2-guard', 'jenny-owner-q3-speed'])).map((c) => c.id)).not.toContain('jenny-owner-q4-ada')
  })
  it('remembers guards, Ruth being admitted and external power-cut rescue', () => {
    const third = play(['jenny-q1-owner', 'jenny-owner-q2-guard'])
    expect(body(third)).toMatch(/护罩/)
    const fifth = pick(pick(third, 'jenny-owner-q3-open-door'), 'jenny-owner-q4-power')
    expect(body(fifth)).toMatch(/鲁思/)
    expect(body(pick(fifth, 'jenny-owner-q5-blame'))).toMatch(/埃莉诺.*(总闸|动力)/)
  })
  it('requires restoration before testing a removed gear and keeps partial terms partial', () => {
    const before = play(['jenny-q1-workers', 'jenny-workers-q2-dismantle'])
    expect(body(result(before, 'jenny-workers-q3-test'))).toMatch(/(装回|复原).*齿轮|齿轮.*(装回|复原)/)
    const end = pick(pick(pick(before, 'jenny-workers-q3-test'), 'jenny-workers-q4-restore'), 'jenny-workers-q5-share')
    expect(body(end)).toMatch(/齿轮|主传动/)
    const partial = play(['jenny-q1-workers', 'jenny-workers-q2-terms', 'jenny-workers-q3-conditional', 'jenny-workers-q4-direct', 'jenny-workers-q5-share'])
    expect(body(partial)).toMatch(/只签.*培训|同薪.*未|赔偿.*未/)
    expect(body(partial)).toMatch(/鲁思.*备用/)
  })
  it('keeps characters at their chosen machine and does not rescue the unknown site by assertion', () => {
    const visited = play(['jenny-q1-open', 'jenny-open-q2-visit'])
    expect(body(visited)).toMatch(/仿制.*(看|查|去|返回)|返回.*原机/)
    const atCopy = pick(visited, 'jenny-open-q3-copy')
    expect(body(atCopy)).toMatch(/你.*仿制|仿制.*你/)
    const ending = pick(pick(atCopy, 'jenny-open-q4-copy'), 'jenny-open-q5-standard')
    expect(body(ending)).toMatch(/仿制.*停/)
    expect(body(ending)).toMatch(/原机.*(另|未|待)|另.*原机/)
    expect(body(ending)).not.toContain('再没有工坊能')
    const withPage = play(['jenny-q1-open', 'jenny-open-q2-note', 'jenny-open-q3-original'])
    expect(options(withPage).map((c) => c.id)).toContain('jenny-open-q4-card')
    expect(options(atCopy).map((c) => c.id)).not.toContain('jenny-open-q4-card')
  })
  it('legacy untrained save and relic-only instruction do not count as a completed drill', () => {
    expect(options(legacy('q4-owner', ['routeOwner', 'fullSpeed'])).map((c) => c.id)).not.toContain('jenny-owner-q4-ada')
    let state = play(['jenny-q1-owner'])
    state = pick(state, 'use-spinning-jenny-owner-anonymous-dose', ['anonymous-dose'])
    const untrained = pick(state, 'jenny-owner-q3-speed')
    expect(options(untrained).map((c) => c.id)).not.toContain('execute-spinning-jenny-owner-anonymous-dose')
    const trained = pick(state, 'follow-spinning-jenny-owner-anonymous-dose')
    const final = pick(trained, 'execute-spinning-jenny-owner-anonymous-dose')
    expect(final.tags).not.toContain('adaTrained')
    expect(body(pick(final, 'jenny-owner-q5-blame'))).toMatch(/接手者.*停下|艾达.*松轴/)
  })
  for (const relic of ['', 'signed-prescription', 'anonymous-dose', 'prison-thread']) it(`all paths / ${relic}`, () => verifyPaths(episode, relic))
})
